# server config
server:
  port: 80

# log config
logging:
  file: banana.log

#spring config
spring:
  thymeleaf:
    cache: false
#  datasource:
#    url: jdbc:h2:file:./example/db/banana
#    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:mysql://localhost:3306/banana?&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: Hongdou@521
#    hikari:
#      maximum-pool-size: 30


banana:
  security:
    welcomePage: /page/index
    auth:
      loginPage: /page/auth
      loginRequestType: ajax
      types:
        mobile:
          #配置 Filter的processUrl和参数名
          authRequestUrl: /auth/mobile
          paramsName: mobile
        default:
          authRequestUrl: /auth/account
          paramsName:
    signOut:
      signOutUrl: /signout
      requestType: form
    captcha:
      sms:
        paramName: validate_code
        length: 4
        uri: /api/auth/mobile,/auth/mobile
        requestUri: /captcha/sms
      image:
        paramName: validate_code
        width: 118
        height: 42
        length: 6
        uri: /api/auth/account,/auth/account
        requestUri: /captcha/image
    social:
      signUpPage: /page/signup
      signUpRequestUrl: /user/signup
      bindingRequestUrl: /user/binding
      socials:
        oicq:
          appId: 101515942
          app-secret: ddd6db3ef19c2963b54088059652ce75
          providerId: oicq
          processUrls: /auth

