# server config
server:
  port: 8090

# log config
logging:
  file: banana.log

#spring config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banana?&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Hongdou@521
    hikari:
      maximum-pool-size: 30
  thymeleaf:
    cache: false

#banana security config
security:
  requestUriWithAjax: /api
  loginPage: /page/login
  welcomePage: /page/index
  authRequestUri: /api/auth
